type_pattern:
  - chain
  - star
  - clique

num_elements: 
  - 2
  - 3
  - 4
  
nodes_per_element: 
  - 3
  - 4
  - 5
  
num_nodes: 30
size_node: 400
size_border_node: 1
color_node: "#fff"
color_label: "black"
color_edge: "black"
arrowsize: 15
total_graph: 10
